### PR TITLE
Update OS X to macOS

### LINKED ISSUE #1215: OS X should be macOS
## Summary

Simple, semantic issue. As of the release of macOS Sierra 10.12.0 earlier this year, OS X is now called macOS.

## Process

Visit the [Create a USB stick on OS X | Ubuntu](https://www.ubuntu.com/download/desktop/create-a-usb-stick-on-mac-osx) page.

## Current and expected result

It said OS X but I was expecting macOS.

## Screenshot
screen shot 2016-12-20 at 10 15 30

### PR DESCRIPTION
**Pull request by larouxn**
## Done

Updated instances of `OS X` to `macOS`, created new screenshots for the USB guide, renamed old OS X files, and updated the redirects file.
2_password
3_select_diskimage
4_select_iso_file
5_select_drive
6_finished

## QA

Visit:

- [https://www.ubuntu.com/download/desktop/create-a-usb-stick-on-macos](https://www.ubuntu.com/download/desktop/create-a-usb-stick-on-macos)
- [https://www.ubuntu.com/download/desktop/burn-a-dvd-on-macos](https://www.ubuntu.com/download/desktop/burn-a-dvd-on-macos)

## Issue / Card

Resolves #1215 

## Screenshots
screen shot 2016-12-21 at 15 11 47

### CODE REVIEW

**Comment by larouxn** [comment]
Looks like there's another page for creating a DVD on macOS (OS X). I need to update that page as well.

**Comment by nottrobin** [comment]
@larouxn thanks for this great work.

I've uploaded your images to the assets server:

- https://assets.ubuntu.com/v1/081c9922-osascript-auth.png
- https://assets.ubuntu.com/v1/c9cf468c-unetbootin.png
- https://assets.ubuntu.com/v1/7cd52408-open-iso.png
- https://assets.ubuntu.com/v1/888e8078-unetbootin-after.png
- https://assets.ubuntu.com/v1/a61982c5-installation-complete.png

If you have time to update them in this PR then I'll happily review the work.

I don't have a strong opinion about the filenames, but if you really want to rename them, you can mitigate any SEO impact by adding redirects to [redirects.yaml](https://github.com/ubuntudesign/www.ubuntu.com/blob/master/redirects.yaml).

**Comment by nottrobin** [comment]
Fixes #1215

**Comment by larouxn** [comment]
@nottrobin, thanks for uploading my screenshots. I updated all the screenshot links, renamed the two OS X files, and added redirects for the old filenames.

**Comment by nottrobin** [comment]
thanks for all the great work @larouxn. I've merged this and I'll release it now.

**Comment by nottrobin** [comment]
Those changes went live: https://www.ubuntu.com/download/desktop/create-a-usb-stick-on-macos

**Comment by larouxn** [comment]
No worries @nottrobin, glad to help out. Thanks for the assistance. 😃

**Pull request merged**
