### PR TITLE
Add border to the bottom of the hero row

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
- Added a border to small screen hero section in mobile section

## QA
- Pull down this branch and run `make run`
- Go to http://127.0.0.1:8001/mobile
- Check that there is no border at the bottom of the hero section
- Scale the window down and see that the border appears

### CODE REVIEW

**Comment by barrymcgee** [comment]
From a design point of view, should the border sit in the middle? 🤔

https://www.dropbox.com/s/7eh6g99me0gwv5p/Screenshot%202016-12-13%2010.04.26.png?dl=0

**Comment by barrymcgee** [comment]
Aside from that query - all looks good! 👌🏻

**Comment by anthonydillon** [comment]
What do you mean in the middle? Does it look like the two images are in the
same row?

**Comment by anthonydillon** [comment]
Superseded by #1193

**Pull request closed without merging**
