### PR TITLE
add japanese AU service description and tidied up the UA indentation

### PR DESCRIPTION
**Pull request by deadlight**
## Done

 - Added new Japanese service description for UA
 - Fixed issues in files I touched

## QA

 - Go to `http://10.20.66.17:8001/legal/ubuntu-advantage/service-description` click the link in "Japanese translation"
 - Check that the Japanese page displays correctly
 - Check the content against the [copydoc](https://docs.google.com/document/d/1Tpf4FuP6SzvfyFw-nlR44uAIkofNdwzDaJFY36ZAk68/edit#) as much as you are able.

### CODE REVIEW

**Comment by deadlight** [comment]
@magdalena-mirowicz Can you comment here when the translators have signed this off, please.

**Comment by anthonydillon** [comment]
@deadlight Sorry, looks like there are conflicts in the branch. Please fix before I review.

**Comment by barrymcgee** [comment]
Code all looks good but very difficult to verify quality of Japanese copy - I assume a Japanese speaker will have seen a demo page?

**Comment by deadlight** [comment]
@barrymcgee yes: we've done rounds of checks with a Japanese proof-reader.

**Pull request merged**
