### PR TITLE
Cloud training updates

### PR DESCRIPTION
**Pull request by grahambancroft**
## Done

Update OpenStack onsite training details as per updated copy doc
Drive by: Increase bottom margin of the first divided div, to make is the same as the bottom padding

## QA

Check that the recent changes to the copy doc have been mirrored in the /cloud/openstack/training/index.html file

## Issue / Card

Card: https://trello.com/c/NULh7MDp
Doc: https://docs.google.com/document/d/1gyxy75qXC5Ta08o6Vnm13yK6aeN4qOnsETB2gZ4e0ZY/edit

### CODE REVIEW

**Comment by grahambancroft** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;NULh7MDp&#x2F;1302-updates-to-cloud-training"> updates to &#x2F;cloud&#x2F;training</a>

**Comment by barrymcgee** [comment]
Bottom padding looks out to me?

**Comment by barrymcgee** [comment]
screenshot 2016-07-08 14 52 06

**Comment by barrymcgee** [comment]
Code looks good apart from that

**Comment by grahambancroft** [comment]
I’m seeing the same on live, are you happy for me to merge this and I’ll get an issue in to fix the padding?

**Comment by barrymcgee** [comment]
@grahambancroft Yep, fine

**Pull request merged**
