### PR TITLE
more scss clean-ups around cloud and removing unused widgets.scss

### PR DESCRIPTION
**Pull request by pmahnke**
## Done
- re-tidied and linted _local.scss
- removed unused _widget.scss
- added strip-inner-wrapper to two /cloud thank you pages
## QA
1. no css should have changed, so a general look around should do
2. look at the two /cloud pages (/cloud/openstack/managed-cloud/thank-you.html and /cloud/newsletter-thank-you.html) and see they are ok

### CODE REVIEW

**Comment by deadlight** [comment]
@pmahnke I'd happily review this again if you find time to fix the conflict. 

Also, we discussed PR sizes in dev catch-up and, despite the overhead of creating them, mostly unrelated changes would be better in different PRs (most of this work not conflicting and landable being a case-in-point).

**Comment by pmahnke** [comment]
@deadlight this is ready again.... I think

**Comment by deadlight** [comment]
Sorry, there's an [issue on /cloud/newsletter-thank-you](http://www.awesomescreenshot.com/image/1808056/d07b264e4e0e22623550e4f0a8cf6986)

**Comment by pmahnke** [comment]
@deadlight fixed

image

I am pretty sure I fixed that originally... strange.

Peter

**Pull request merged**
