### PR TITLE
MAAS takeover

### PR DESCRIPTION
**Pull request by grahambancroft**
## Done

Reinstate old MAAS takeover to become generic

## QA

Check the takeover in s/m/l

Already had design approval from Yaili

## Issue / Card

Flickr screen shot of original: https://www.flickr.com/photos/mahnke/24367777672/in/album-72157632132960058/
Card: https://trello.com/c/FGRxMWCV

### CODE REVIEW

**Comment by grahambancroft** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;FGRxMWCV&#x2F;1332-cloud-generic-takeover-maas"> cloud generic takeover: Maas</a>

**Comment by grahambancroft** [comment]
Demo here http://www.ubuntu.com-maas-takeover.demo.haus/

**Comment by barrymcgee** [comment]
LGTM! :shipit:

@grahambancroft Just need to resolve conflicts first

**Comment by grahambancroft** [comment]
Fab, thank you. Conflicts resolved, merging

**Pull request merged**
