### PR TITLE
update /cloud events

### PR DESCRIPTION
**Pull request by pmahnke**
## Done

* updated the /cloud overview events

## QA

1. go to /cloud
2. see that all the events are current

## Issue / Card

[trello card](https://trello.com/c/NR8J87s9)

### CODE REVIEW

**Comment by pmahnke** [comment]
[update /cloud events](https://trello.com/c/NR8J87s9/1837-update-cloud-events)

**Comment by anthonydillon** [comment]
It doesnt look like this has the latest events in it. Seems to be missing:
- Huawei Connect Europe
- Enterprise Open Source Roadshow – Espoo
- Enterprise Open Source Roadshow – Zurich event

Is there a reason for this?
Seen at the bottom of https://insights.ubuntu.com/cloud-and-server

**Comment by pmahnke** [comment]
@anthonydillon I get the events from https://insights.ubuntu.com/category/events/feed/?group=cloud-and-server&2016-10-20d0000=true

I think you have uncovered an insights bug that is showing non cloud and server events on the cloud and server page...

I think my list is more correct.

**Comment by anthonydillon** [comment]
I think the feed you are using is wrong. The first event [1] has Cloud and server as a tag and is not shown on your list.

[1] https://insights.ubuntu.com/event/enterprise-open-source-roadshow-10/

**Comment by pmahnke** [comment]
@anthonydillon well... I would still say that is an insights bug that it isn't in that feed... but on a practical level, I think promoting ODS over a sales event in Finland is the right thing now.

**Pull request merged**
