### PR TITLE
Bootstack takeover

### PR DESCRIPTION
**Pull request by grahambancroft**
## Done

Reinstate old Bootstack takeover to become generic Bootstack takeover

## QA

Check the takeover in s/m/l

Already had design approval from Yaili

## Issue / Card

Flickr screen shot of original: https://www.flickr.com/photos/mahnke/21450032221/in/album-72157632132960058/
Card: https://trello.com/c/DUQnJrhS

### CODE REVIEW

**Comment by grahambancroft** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;DUQnJrhS&#x2F;1331-cloud-generic-takeover-bootstack"> cloud generic takeover: Bootstack</a>

**Comment by barrymcgee** [comment]
@grahambancroft Does this need to be included in the homepage to QA? 🤔

**Comment by grahambancroft** [comment]
@barrymcgee It does, there’s a Yaili approved demo here http://www.ubuntu.com-bootstack-takeover.demo.haus/

**Comment by barrymcgee** [comment]
LGTM! :shipit:

**Pull request merged**
