### PR TITLE
Server full width

### PR DESCRIPTION
**Pull request by grahambancroft**
## Done

Make server section full width

## QA

Check the server section in s/m & l

## Issue / Card

Card: https://trello.com/c/6aU6HEyP

### CODE REVIEW

**Comment by grahambancroft** [comment]
[Server section full width](https://trello.com/c/6aU6HEyP/1788-server-section-full-width)

**Comment by anthonydillon** [comment]
ubuntu server and hyperscale server ubuntu

**Comment by grahambancroft** [comment]
@anthonydillon Ugh, fixed now :)

**Comment by anthonydillon** [comment]
Perfect thanks :+1:

**Pull request merged**
